
get http://localhost:8000/api/companies

###
GET http://localhost:8000/api/investments

###
POST http://localhost:8000/api/investments
Content-Type: application/json

{
  "startUpId": 1,
  "name": "haechan",
  "investAmount": 5000,
  "comment": "test POST",
  "password": "1234"
}

